server:
  port: 8082

spring:
    application:
        name: book-service
    datasource:
        url: jdbc:postgresql://localhost:5432/bookdb
        username: bookuser
        password: bookpassword
    jpa:
        hibernate:
        ddl-auto: update
        show-sql: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/